export const CollectionToUpdateAuthority = {
    'Solana Monkey Business': '9uBX3ASjxWvNBAD1xjbVaKA74mWGZys3RGSF7DdeDD3F',
    'Degenerate Ape Academy': 'DC2mkgwhy56w3viNtHDjJQmc7SGu2QX785bS4aexojwX',
    'Galactic Gecko Space Garage': 'CeS4fWuRz44kUf5aHJZW62LD8GJkPabLsChA5Zn2rLiS',
    'thugbirdz': ['AvkbtawpmMSy571f71WsWEn41ATHg5iHw27LoYJdk8QA', 'CzrE3LhijwcmvsXZa8YavqgR9EzW3UGqoSWZKwGpZVqM'],
    'Aurory': 'aury7LJUae7a92PBo35vVbP61GX8VbyxFKausvUtBrt',
    'Solarians': '4nuNUbvQQ6hsYLFB9yAeDdhHRbbxa3vHQwhBbMkD66Sf',
    'Infinity Labs': 'BnRLyz8RfULs4phucV9EzmDNkMNg96D5yQtg7cZ9BBZo',
    'Bold Badgers': 'TESAinbTL2eBLkWqyGA82y1RS6kArHvuYWfkL9dKkbs',
    'SolPunks': 'F5FKqzjucNDYymjHLxMR2uBT43QmaqBAMJwjwkvRRw4A',
    'SolSteads': 'ASBsEqEw5bWD2rpiq4JgF8pBjBDVFMDFS5eXXyVf3gDF',
    'Piggy Sol Gang': 'Pigv3gFWLWJL8QwrFBkdZLe1RYzNJTSJPGEUNVimJjh',
    'Frakt': '6wPYbuGRXZjVw2tCeTxwRiQU7AzFDTeFEKuUFpJZpcix',
    'Sollamas': 'LamapQPXuMYEuvsyZqK2UPqn1XCT2sW1soURj7ZJkZF',
    'Stylish Studs': '9VvPQMGVuggHwDZNfEVJH63incwSSA477AMKo5XaiCDh',
    'Red Panda Squad': '9gFTByoawNgJFB1psDgN5WqyUebJacqeL8Avmr1GChY9',
    'Abstratica': 'absF5t1MP7dXFhbgUgaTi7ffJM2WhBg1cmrY5s7h3By',
    'Turtles': '5CtJuju8PSun4XnA5LzzfLoQKBBZAS84UUjeMWwoUxNj',
    'SolSnatchers': '4drW3cpobroupcN5188QP1dTTkaXxJrge6v9kZDpiLJQ',
    'Solana Valley': '7cSycnDQjX7oRnLB2MeoVfuDfz8ab4wpmocoE8UCwmUM',
    'Tuco & the Gravestones': 'LLAmArGWBCspEarLTCBpKLdXxYS4EUuiQZQmy1RD8oc',
    'Playground Waves': 'Edy3xedybSQYAE6eboza5YEcoJan91nfSd3jUppHz7u1',
    'SolSouls': '9doSyLpnDtAB4R1CVmKjwqUWP6oJ8huB1SSJksthYPS',
    'Fancy Frenchies': '3RP7R6PaxtrgRELSoiVZjoNf1MuXrpB1ptz3tfc1Pqyt',
    'Trippy Bunny Tribe': 'AumNBDNhvvknpcK9Zg6YeX9FrEoXtDE1f4rhK4qfVoyp',
    'SolanaDogeNFTs': 'HwMBMB6QpPJNyFnbVtt2UKVmJQPGnKKsMfaxNUyWahmc',
    'The Sneks': 'DYWwMTH4J8Xr7qvpTjiQBjFbAqrDaHvdGqrhriLRrzxz',
    'Crypto Cavemen': '7gbxCxJkWcop1FCoaHnB6JJaRjpnkMxJFNbqtTS8KJbD',
    'Crypto Cubs': 'E4ca1QgJdpGaMfRWYcdKpMAWWurJ3YhVJHg4wXUw7pAW',
    'Eternal Beings': '3zP2zyuEqg2Kc7ZcyuTSffJpBnWDw9R6aoVhDiAYEFd4',
    'Legion Punks': 'GKqHTZ6WXjCc1BbRBR4W1GSW1iWkxxdmDEHvmKkrLtcL',
    'gmoot': '2MUpR2xj5FjzL13NiZa852nzwtNTb1FKVf1ERKSvZKd8',
    'Kaiju Cards': 'FGr9rJSQFP4ypFbJMhCotZh94ciMvcU3dApuDeXRi6vb',
    'Solamanders': '8SLd4WPgLRvLJZTAU1jr4BofjRpK6jF7rgUaHen8Gmuw',
    'Solantasy': 'xhfWZKQJZJydnHQ2mTLzRqDUFZeiDG1nrFSsfjasdxt',
    'SolBears': '8749adNqCXzVjdYVCUFcjUUxsPcHuCW482roGqsxtMRX',
    'Sol Chicks': '7BPrveGEsNmr5UU2bSzSmHh8wbhB1NWTw4dXqykqpm1e',
    'Crypto Idolz': '63DCfJUUqe9ANLCZnTr487NaQMsgqrCtARAfVWhHfSAa',
    'SolSocks': '8VNw672YiTa7X4QN7sVt2NAFq8fQ8bc5HXxDZp2kxY36',
    'ROX': 'AjMom2yKn2Bn4z182g2nRmKWWvGaQ8q2UNKucMetEWjj',
    'Cyber Samurai': 'JM4KXKpHzUk4KziUGBBCnnKFeLzLiaJyttTGRuF9Pn9',
    'Panda Fraternity': 'Abexia3xiTtDbfZ25M3pwD7VFn8E3mcKXFHcKZqo9jeP',
    'Lunaria': 'G5hHMtNkWDWkF5Ab5YdTexJKZZvFKqwQ1kRxW4ukDzRV',
    'Panda Street': 'J6JPuP91cRdPEWYWN1isvctDGXBEuV7azq1BZAb2dsJX',
    'Lit Jesus': '2Qkgc2DK9JSWbpzrRHWbsgd1NWDV4qoyWAg68cW8qWLG',
    'Cool Beans': 'BUMHapcWgV1KgW6aEVjUugsWBYeZMUocGkNEoQhxvUWa',
    'Solanauts': 'Dj13m8RJwtjkWsXY9LhiPaeVpqT6tq9yS4r6bb8MHi4y',
    'Synapses': '6b3uF4TR3Z6bRL1xK7VPuszk6iqepaZqQgQAFpyYtDny',
    'ApeShit Social Club': 'H8EdyqLJTBrCYjuydt2f4BtRTEeBTXVd9oyNuYZNfuaD',
    'Contrastive': '8UvjZ1dzn9bjuSYrRs5rk7KBPKodp2ieTpT68ctYiWWU',
    'Flunk Donkeys': 'FLUNK9i7TNDV6C8n73yoRTJXb9mt2JCqEoBkCVZ7ipDK',
    'ShroomZ': 'CN47yMZHZ2KayDTtrMa5VkKJzTYHETiPCVayhKWan7PQ',
    'SolAnimals': 'Gen1x34u5gNvBtSLJ2J3AWnFdCU2D7oPLrh84orRC58',
    'Sol Lions': '4KoWqe88Mg5EmUWXeEMQahKQgfnNWK8Wd3AEq2rBAAfK',
    'SSBxSolPunks': 'F5FKqzjucNDYymjHLxMR2uBT43QmaqBAMJwjwkvRRw4A',
    'SolStash': 'C5ruRv8VMhLL4WuSVH8jKFGBtbSUQCfFvbojKh7UfXq4',
    'Pixel Dudes': '3anukDBEijov9oVBNNbvCYsUkBc7yYioiCZiGvuWw61e',
    'Kreechures': '9dMJRRqpWEHL3nekRQMYpWFVLYiGKtdozcFCbMk298p3'
}